name = "KhepriFrame4DD"
uuid = "facca88e-a9e2-48fe-94cb-e86d30575c40"
authors = ["António Menezes Leitão <antonio.menezes.leitao@gmail.com>"]
version = "0.2.0"

[deps]
ColorTypes = "3da002f7-5984-5a60-b8a6-cbb66c0b333f"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Frame4DD = "70a0cd9f-3d70-4b89-ad90-2d0d49bb6120"
KhepriBase = "4cc0fe96-1163-46f3-ba32-de1e65d9548f"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"

[compat]
ColorTypes = "0.11"
KhepriBase = "0.7"
Reexport = "1.2"
julia = "1.12"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
